language: python

python:
    - 3.7

script:
    - python _runner_tests.py
    - python contemplate_koans.py about_asserts
    - python contemplate_koans.py about_strings

notifications:
  email: true
